language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_URL=https://evizi.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    - GIT_BRANCH=${TRAVIS_BRANCH}
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  - make ci
